[tool.poetry]
name = "contract-analysis"
version = "0.1.0"
description = "This is a service to detect and analyze Solidty smart contracts with known vulnerabilities."
authors = ["Jason Sun <sunapi386@gmail.com>"]
readme = "README.md"
packages = [{include = "contract_analysis"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.98.0"
uvicorn = "^0.22.0"
black = "^23.3.0"
requests = "^2.31.0"
python-multipart = "^0.0.6"
langchain = "^0.0.212"
llama-index = "^0.6.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
